-- MedGuide fresh Supabase setup
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.clinics (
  id bigint generated by default as identity primary key,
  name text not null,
  type text default 'Clinic',
  address text default '',
  city text default '',
  distance_km numeric default 0,
  rating numeric default 0,
  reviews_count integer default 0,
  verified boolean default false,
  open_hours text default '',
  phone text default '',
  specialties text[] default '{}',
  fee_from numeric default 0,
  emergency_24x7 boolean default false
);

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  clinic_id bigint references public.clinics(id) on delete cascade,
  name text not null,
  specialty text default '',
  qualification text default '',
  exp_years integer default 0,
  rating numeric default 0,
  consult_fee numeric default 0,
  video_fee numeric default 0,
  available_days text default ''
);

create table if not exists public.pharmacy_stock (
  id bigint generated by default as identity primary key,
  clinic_id bigint references public.clinics(id) on delete cascade,
  medicine text not null,
  composition text default '',
  price numeric default 0,
  in_stock boolean default true,
  qty integer default 0
);

create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  composition text not null,
  strength text default '',
  brand text not null,
  maker text default '',
  pack text default '',
  price numeric default 0,
  mrp numeric default 0,
  generic boolean default false,
  jan_aushadhi boolean default false,
  rating numeric default 0,
  category text default ''
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_name text default '',
  phone text default '',
  clinic_id bigint references public.clinics(id) on delete set null,
  doctor_id bigint references public.doctors(id) on delete set null,
  date text not null,
  slot text not null,
  status text default 'confirmed',
  created_at timestamptz default now()
);

create table if not exists public.clinic_reviews (
  id bigint generated by default as identity primary key,
  clinic_id bigint references public.clinics(id) on delete cascade,
  user_name text not null,
  rating integer not null,
  comment text default '',
  created_at timestamptz default now()
);

create table if not exists public.family_members (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  relation text default '',
  age integer,
  blood_group text default '',
  conditions text default '',
  created_at timestamptz default now()
);

create table if not exists public.health_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  issue text default '',
  triage text default 'green',
  severity integer default 1,
  days text default '',
  language text default 'en',
  advice text default '',
  attachment_url text default '',
  source text default 'manual',
  created_at timestamptz default now()
);

create table if not exists public.sos_contacts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  phone text not null,
  relation text default '',
  created_at timestamptz default now()
);

create table if not exists public.sos_alerts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  lat text default '',
  lng text default '',
  address_text text default '',
  note text default '',
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  plan text not null,
  price numeric default 0,
  total integer default 0,
  used integer default 0,
  expires_at text default '',
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists public.video_consults (
  id bigint generated by default as identity primary key,
  user_id text not null,
  doctor_id bigint references public.doctors(id) on delete set null,
  topic text not null,
  scheduled_at text default '',
  duration_min integer default 10,
  status text default 'scheduled',
  link text default '',
  notes text default '',
  created_at timestamptz default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  city text default '',
  rating integer default 5,
  message text not null,
  tag text default 'MedGuide User',
  approved boolean default true,
  created_at timestamptz default now()
);

insert into storage.buckets (id, name, public)
values ('medguide-uploads', 'medguide-uploads', true)
on conflict (id) do update set public = excluded.public;

-- Starter data so directory, medicine comparison and video-consult screens are usable immediately.
insert into public.clinics (id,name,type,address,city,distance_km,rating,reviews_count,verified,open_hours,phone,specialties,fee_from,emergency_24x7)
values
  (1,'MedGuide City Clinic','Multi-speciality','Sector 18','Noida',2.4,4.7,128,true,'08:00 AM - 10:00 PM','9876543210',array['General Medicine','Pediatrics','Dermatology'],300,true),
  (2,'Swasthya Care Centre','Clinic','Indirapuram','Ghaziabad',5.1,4.5,86,true,'09:00 AM - 08:00 PM','9876543211',array['General Medicine','ENT'],250,false)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.clinics','id'), greatest((select coalesce(max(id),1) from public.clinics),1));

insert into public.doctors (clinic_id,name,specialty,qualification,exp_years,rating,consult_fee,video_fee,available_days)
select 1,'Dr. A. Sharma','General Medicine','MBBS, MD',12,4.8,500,299,'Mon-Sat' where not exists (select 1 from public.doctors where name='Dr. A. Sharma');
insert into public.doctors (clinic_id,name,specialty,qualification,exp_years,rating,consult_fee,video_fee,available_days)
select 1,'Dr. Neha Verma','Pediatrics','MBBS, MD Pediatrics',9,4.7,600,349,'Mon-Fri' where not exists (select 1 from public.doctors where name='Dr. Neha Verma');
insert into public.doctors (clinic_id,name,specialty,qualification,exp_years,rating,consult_fee,video_fee,available_days)
select 2,'Dr. R. Khan','ENT','MBBS, MS ENT',10,4.6,450,249,'Tue-Sun' where not exists (select 1 from public.doctors where name='Dr. R. Khan');

insert into public.medicines (composition,strength,brand,maker,pack,price,mrp,generic,jan_aushadhi,rating,category)
select 'Paracetamol','500 mg','Jan Aushadhi Paracetamol','PMBI','10 tablets',8,10,true,true,4.7,'Fever/Pain' where not exists (select 1 from public.medicines where brand='Jan Aushadhi Paracetamol');
insert into public.medicines (composition,strength,brand,maker,pack,price,mrp,generic,jan_aushadhi,rating,category)
select 'Paracetamol','500 mg','Paracare 500','Demo Pharma','10 tablets',24,28,false,false,4.5,'Fever/Pain' where not exists (select 1 from public.medicines where brand='Paracare 500');
insert into public.medicines (composition,strength,brand,maker,pack,price,mrp,generic,jan_aushadhi,rating,category)
select 'Cetirizine','10 mg','Jan Aushadhi Cetirizine','PMBI','10 tablets',10,12,true,true,4.6,'Allergy' where not exists (select 1 from public.medicines where brand='Jan Aushadhi Cetirizine');
insert into public.medicines (composition,strength,brand,maker,pack,price,mrp,generic,jan_aushadhi,rating,category)
select 'Cetirizine','10 mg','Cetzine Demo','Demo Pharma','10 tablets',32,38,false,false,4.4,'Allergy' where not exists (select 1 from public.medicines where brand='Cetzine Demo');

insert into public.pharmacy_stock (clinic_id,medicine,composition,price,in_stock,qty)
select 1,'Paracetamol 500','Paracetamol',8,true,50 where not exists (select 1 from public.pharmacy_stock where clinic_id=1 and medicine='Paracetamol 500');
insert into public.pharmacy_stock (clinic_id,medicine,composition,price,in_stock,qty)
select 1,'Cetirizine 10','Cetirizine',10,true,25 where not exists (select 1 from public.pharmacy_stock where clinic_id=1 and medicine='Cetirizine 10');

insert into public.testimonials (name,city,rating,message,tag,approved)
select 'Demo User','Noida',5,'Simple interface and useful health guidance.','MedGuide User',true where not exists (select 1 from public.testimonials where name='Demo User');
