import { Link } from 'react-router-dom';
import { Pill, ShieldAlert, ArrowUpRight, CheckCircle2 } from 'lucide-react';
import { useLanguage } from '../lib/language';

type Assessment = { urgency: 'green' | 'yellow' | 'red'; summary?: string; possibleCauses?: { name: string }[]; detectedSymptoms?: string[] };
const copy = {
  en: ['Medicine and self-care guidance', 'This is symptom-based general information, not a prescription or a confirmed diagnosis.', 'Ask a pharmacist or doctor before taking a medicine, especially for children, pregnancy, chronic illness, allergies or other medications.', 'Check the label for ingredients, age restrictions, warnings and maximum dose. Do not combine products containing the same active ingredient.', 'Seek urgent medical care first. Do not delay emergency treatment to try medicine.', 'No medicine can be safely selected from these symptoms alone. Ask a qualified clinician or pharmacist.', 'Explore official Jan Aushadhi catalogue', 'Possible supportive option', 'Do not start antibiotics, steroids or prescription medicines without a clinician.'],
  hi: ['दवा और स्व-देखभाल मार्गदर्शन', 'यह लक्षणों पर आधारित सामान्य जानकारी है, डॉक्टर की पर्ची या निश्चित निदान नहीं।', 'बच्चों, गर्भावस्था, पुरानी बीमारी, एलर्जी या अन्य दवाएं लेने पर पहले डॉक्टर या फार्मासिस्ट से पूछें।', 'दवा के लेबल पर घटक, उम्र की सीमा, चेतावनियां और अधिकतम मात्रा जांचें। समान घटक वाली दवाएं साथ न लें।', 'पहले तत्काल चिकित्सा सहायता लें। दवा आजमाने के लिए इलाज में देरी न करें।', 'इन लक्षणों से अकेले सुरक्षित दवा तय नहीं की जा सकती। डॉक्टर या फार्मासिस्ट से पूछें।', 'आधिकारिक जन औषधि कैटलॉग देखें', 'संभावित सहायक विकल्प', 'बिना डॉक्टर की सलाह के एंटीबायोटिक, स्टेरॉयड या प्रिस्क्रिप्शन दवाएं शुरू न करें।'],
  hinglish: ['Medicine aur self-care guidance', 'Ye symptoms par based general information hai, prescription ya confirmed diagnosis nahi.', 'Bachchon, pregnancy, chronic illness, allergies ya doosri medicines ke case mein doctor/pharmacist se poochhein.', 'Label par ingredients, age restrictions, warnings aur maximum dose check karein. Same ingredient wali medicines combine na karein.', 'Pehle emergency care lein. Medicine try karne ke liye treatment delay na karein.', 'Sirf in symptoms se safe medicine decide nahi ho sakti. Doctor ya pharmacist se poochhein.', 'Official Jan Aushadhi catalogue dekhein', 'Possible supportive option', 'Doctor ke bina antibiotics, steroids ya prescription medicines shuru na karein.'],
  mr: ['औषधे आणि स्व-काळजी मार्गदर्शन', 'ही लक्षणांवर आधारित सामान्य माहिती आहे; प्रिस्क्रिप्शन किंवा निश्चित निदान नाही.', 'लहान मुले, गर्भावस्था, जुनाट आजार, अॅलर्जी किंवा इतर औषधे असल्यास डॉक्टर किंवा फार्मासिस्टचा सल्ला घ्या.', 'लेबलवरील घटक, वयोमर्यादा, सूचना आणि कमाल मात्रा तपासा. समान घटक असलेली औषधे एकत्र घेऊ नका.', 'आधी तातडीची वैद्यकीय मदत घ्या. औषध वापरून पाहण्यासाठी उपचार पुढे ढकलू नका.', 'फक्त या लक्षणांवरून सुरक्षित औषध ठरवता येत नाही. डॉक्टरांचा सल्ला घ्या.', 'अधिकृत जन औषधी सूची पहा', 'संभाव्य सहाय्यक पर्याय', 'डॉक्टरांशिवाय अँटिबायोटिक्स, स्टेरॉइड्स किंवा प्रिस्क्रिप्शन औषधे सुरू करू नका.'],
  ta: ['மருந்து மற்றும் சுய பராமரிப்பு வழிகாட்டல்', 'இது அறிகுறிகளின் அடிப்படையிலான பொதுத் தகவல் மட்டுமே; மருந்துச் சீட்டோ உறுதியான நோயறிதலோ அல்ல.', 'குழந்தைகள், கர்ப்பம், நீண்டகால நோய், ஒவ்வாமை அல்லது வேறு மருந்துகள் இருந்தால் மருத்துவர் அல்லது மருந்தாளரிடம் கேளுங்கள்.', 'மருந்து லேபிளில் உள்ள பொருட்கள், வயது வரம்பு, எச்சரிக்கைகள் மற்றும் அதிகபட்ச அளவைச் சரிபார்க்கவும். ஒரே மூலப்பொருள் உள்ள மருந்துகளைச் சேர்க்க வேண்டாம்.', 'முதலில் அவசர மருத்துவ உதவி பெறுங்கள். மருந்தை முயற்சிப்பதற்காக சிகிச்சையைத் தாமதிக்க வேண்டாம்.', 'இந்த அறிகுறிகளைக் கொண்டு மட்டும் பாதுகாப்பான மருந்தைத் தேர்ந்தெடுக்க முடியாது. மருத்துவரிடம் கேளுங்கள்.', 'அதிகாரப்பூர்வ ஜன் ஔஷதி பட்டியலைப் பார்க்கவும்', 'சாத்தியமான ஆதரவு வழி', 'மருத்துவர் ஆலோசனை இல்லாமல் ஆன்டிபயாட்டிக், ஸ்டீராய்டு அல்லது மருந்துச் சீட்டு மருந்துகளைத் தொடங்க வேண்டாம்.'],
  bn: ['ওষুধ ও স্ব-যত্ন নির্দেশনা', 'এটি উপসর্গভিত্তিক সাধারণ তথ্য, প্রেসক্রিপশন বা নিশ্চিত রোগনির্ণয় নয়।', 'শিশু, গর্ভাবস্থা, দীর্ঘস্থায়ী রোগ, অ্যালার্জি বা অন্য ওষুধের ক্ষেত্রে চিকিৎসক বা ফার্মাসিস্টকে জিজ্ঞাসা করুন।', 'লেবেলে উপাদান, বয়সের সীমা, সতর্কতা ও সর্বোচ্চ মাত্রা দেখুন। একই উপাদানের ওষুধ একসঙ্গে নেবেন না।', 'আগে জরুরি চিকিৎসা নিন। ওষুধ পরীক্ষা করতে গিয়ে চিকিৎসায় দেরি করবেন না।', 'শুধু এই উপসর্গ থেকে নিরাপদ ওষুধ বেছে নেওয়া যায় না। চিকিৎসকের পরামর্শ নিন।', 'সরকারি জন ঔষধি ক্যাটালগ দেখুন', 'সম্ভাব্য সহায়ক বিকল্প', 'চিকিৎসকের পরামর্শ ছাড়া অ্যান্টিবায়োটিক, স্টেরয়েড বা প্রেসক্রিপশনের ওষুধ শুরু করবেন না।']
};
const options = [
  { terms: /leg pain|pair me dard|pair mein dard|pair dard|muscle pain|joint pain|body pain|sprain|पैर में दर्द|पैर दर्द|मांसपेश|जोड़ों में दर्द|पाय दुख|கால் வலி|পায়ে ব্যথা/i, labels: ['For mild muscle or leg discomfort, rest and a wrapped cold pack may help. Ask a pharmacist whether paracetamol is appropriate; sudden one-sided swelling, redness, warmth, or chest symptoms need urgent assessment.', 'हल्के पैर या मांसपेशियों के दर्द में आराम और कपड़े में लिपटी ठंडी सिकाई मदद कर सकती है। पैर में अचानक एकतरफा सूजन, लालिमा या सांस की तकलीफ हो तो तुरंत चिकित्सा लें।', 'Mild leg pain mein rest aur cloth-wrapped cold pack help kar sakte hain. Pharmacist se paracetamol ki suitability poochhein. Ek taraf achanak swelling, redness ya saans ki dikkat ho to urgent care lein.', 'पाय दुखत असल्यास विश्रांती व कापडात गुंडाळलेला थंड शेक उपयोगी पडू शकतो. अचानक एकतर्फी सूज किंवा श्वास घेण्यास त्रास असल्यास तातडीने तपासणी करा.', 'லேசான கால் வலிக்கு ஓய்வும் துணியில் சுற்றிய குளிர் ஒத்தடமும் உதவலாம். திடீர் ஒரு பக்க வீக்கம் அல்லது மூச்சுத் திணறலுக்கு உடனடி மருத்துவ உதவி பெறவும்.', 'হালকা পায়ের ব্যথায় বিশ্রাম ও কাপড়ে মোড়া ঠান্ডা সেঁক উপকারী হতে পারে। হঠাৎ এক পায়ে ফোলা বা শ্বাসকষ্ট হলে জরুরি চিকিৎসা নিন।'] },
  { terms: /cough|sore throat|खांसी|खाँसी|गले में दर्द|खोकला|இருமல்|কাশি/i, labels: ['Warm fluids and adequate hydration may soothe a mild cough or sore throat. Ask a pharmacist before using cough medicines; breathing difficulty needs urgent care.', 'हल्की खांसी या गले की तकलीफ में गर्म तरल और पर्याप्त पानी मदद कर सकते हैं। खांसी की दवा से पहले फार्मासिस्ट से पूछें।', 'Mild cough mein warm fluids aur hydration help kar sakte hain. Cough medicines ke liye pharmacist se poochhein; breathing difficulty urgent hai.', 'सौम्य खोकल्यासाठी कोमट द्रव व पुरेसे पाणी उपयोगी पडू शकते. औषधापूर्वी फार्मासिस्टचा सल्ला घ्या.', 'லேசான இருமலுக்கு வெதுவெதுப்பான திரவங்கள் உதவலாம். மருந்துக்கு முன் மருந்தாளரிடம் கேளுங்கள்.', 'হালকা কাশিতে উষ্ণ পানীয় ও পর্যাপ্ত পানি উপকারী হতে পারে। ওষুধের আগে ফার্মাসিস্টকে জিজ্ঞাসা করুন।'] },

  { terms: /fever|temperature|बुखार|ताप|காய்ச்சல்|জ্বর/i, labels: ['For fever or discomfort, ask a pharmacist whether paracetamol is suitable for you.', 'बुखार या दर्द में फार्मासिस्ट से पूछें कि पैरासिटामोल आपके लिए उपयुक्त है या नहीं।', 'Fever ya pain mein pharmacist se poochhein ki paracetamol aapke liye suitable hai ya nahi.', 'ताप किंवा वेदनेसाठी पॅरासिटामॉल योग्य आहे का ते फार्मासिस्टला विचारा.', 'காய்ச்சல் அல்லது வலிக்கு பாராசிட்டமால் பொருத்தமா என்று மருந்தாளரிடம் கேளுங்கள்.', 'জ্বর বা ব্যথায় প্যারাসিটামল উপযুক্ত কি না ফার্মাসিস্টকে জিজ্ঞাসা করুন।'] },
  { terms: /diarrh|loose motion|dehydrat|दस्त|दस्त|अतिसार|வயிற்றுப்போக்கு|ডায়রিয়া/i, labels: ['Oral rehydration solution (ORS) may help replace lost fluids. Severe dehydration needs medical care.', 'ORS से पानी और नमक की कमी पूरी करने में मदद मिल सकती है। गंभीर निर्जलीकरण में डॉक्टर से मिलें।', 'ORS lost fluids replace karne mein help kar sakta hai. Severe dehydration mein doctor ko dikhayein.', 'ORS मुळे पाणी आणि क्षारांची कमतरता भरून निघण्यास मदत होऊ शकते.', 'ORS இழந்த நீர்ச்சத்தை ஈடுசெய்ய உதவும். கடுமையான நீரிழப்புக்கு மருத்துவ உதவி தேவை.', 'ORS হারানো পানি ও লবণ পূরণে সাহায্য করতে পারে। গুরুতর পানিশূন্যতায় চিকিৎসা নিন।'] },
  { terms: /blocked nose|nasal congestion|stuffy nose|नाक बंद|नाक बंद|மூக்கடைப்பு|নাক বন্ধ/i, labels: ['Saline nasal spray may help relieve nasal congestion. Follow the product instructions.', 'नाक बंद होने पर सलाइन नेज़ल स्प्रे मदद कर सकता है। लेबल के निर्देश मानें।', 'Blocked nose mein saline nasal spray help kar sakta hai. Label follow karein.', 'नाक बंद असल्यास सलाईन नेझल स्प्रे मदत करू शकतो.', 'மூக்கடைப்புக்கு சலைன் நாசி ஸ்ப்ரே உதவலாம். வழிமுறைகளைப் பின்பற்றவும்.', 'নাক বন্ধ থাকলে স্যালাইন ন্যাজাল স্প্রে সাহায্য করতে পারে। নির্দেশনা মেনে চলুন।'] }
];
export default function SafeMedicineGuidance({ assessment, sourceText = '' }: { assessment: Assessment; sourceText?: string }) {
  const { lang } = useLanguage();
  const languageIndex = ['en', 'hi', 'hinglish', 'mr', 'ta', 'bn'].indexOf(lang);
  const t = copy[lang as keyof typeof copy] || copy.en;
  const text = [sourceText, assessment.summary, ...(assessment.detectedSymptoms || []), ...(assessment.possibleCauses || []).map(item => item.name)].join(' ');
  const matched = assessment.urgency === 'red' ? [] : options.filter(option => option.terms.test(text)).slice(0, 2);
  return <section className="rounded-[28px] border border-emerald-100 bg-white p-5 shadow-lg sm:p-7">
    <div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><Pill size={24}/></div><h2 className="text-xl font-extrabold text-slate-900">{t[0]}</h2></div>
    <p className="mt-3 text-sm leading-6 text-slate-600">{t[1]}</p>
    {assessment.urgency === 'red' ? <div className="mt-4 rounded-xl bg-red-50 p-4 font-bold text-red-800">{t[4]}</div> : matched.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{matched.map((option, index) => <article key={index} className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50 to-white p-4"><div className="flex items-center gap-2 text-emerald-800"><CheckCircle2 size={19}/><p className="text-xs font-extrabold uppercase tracking-wide">{t[7]} {index + 1}</p></div><p className="mt-3 text-sm font-semibold leading-6 text-slate-800">{option.labels[Math.max(0, languageIndex)]}</p><p className="mt-3 rounded-lg bg-white p-2 text-xs text-slate-600">{t[2]}</p></article>)}</div> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-700">{t[5]}</p>}
    <details className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-950"><summary className="flex cursor-pointer items-center gap-2 font-bold"><ShieldAlert size={18}/>{t[3]}</summary><div className="mt-3 space-y-2 pl-6"><p>{t[2]}</p><p>{t[8]}</p></div></details>
    <Link to="/medicines" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-blue-800">{t[6]} <ArrowUpRight size={16}/></Link>
  </section>;
}
